"""Shared constants for skills and position weighting."""

SKILLS = [
    "Conduite de balle",
    "Dribble",
    "Passes courtes",
    "Passes longues",
    "Contrôle orienté",
    "Tir",
    "Vitesse",
    "Agilité",
    "Endurance",
    "Intelligence de jeu",
    "Placement",
    "Jeu collectif",
    "Engagement",
    "Leadership",
    "Attitude / Comportement",
]

POSITION_WEIGHTS = {
    "Gardien": {
        "Conduite de balle": 1,
        "Dribble": 1,
        "Passes courtes": 3,
        "Passes longues": 2,
        "Contrôle orienté": 3,
        "Tir": 1,
        "Vitesse": 3,
        "Agilité": 3,
        "Endurance": 2,
        "Intelligence de jeu": 2,
        "Placement": 3,
        "Jeu collectif": 2,
        "Engagement": 0,
        "Leadership": 0,
        "Attitude / Comportement": 4,
    },
    "Défenseur": {
        "Conduite de balle": 2,
        "Dribble": 2,
        "Passes courtes": 4,
        "Passes longues": 3,
        "Contrôle orienté": 4,
        "Tir": 2,
        "Vitesse": 4,
        "Agilité": 3,
        "Endurance": 3,
        "Intelligence de jeu": 3,
        "Placement": 5,
        "Jeu collectif": 3,
        "Engagement": 0,
        "Leadership": 0,
        "Attitude / Comportement": 4,
    },
    "Milieu": {
        "Conduite de balle": 3,
        "Dribble": 3,
        "Passes courtes": 5,
        "Passes longues": 3,
        "Contrôle orienté": 5,
        "Tir": 3,
        "Vitesse": 3,
        "Agilité": 4,
        "Endurance": 5,
        "Intelligence de jeu": 5,
        "Placement": 4,
        "Jeu collectif": 5,
        "Engagement": 0,
        "Leadership": 0,
        "Attitude / Comportement": 4,
    },
    "Attaquant": {
        "Conduite de balle": 3,
        "Dribble": 4,
        "Passes courtes": 3,
        "Passes longues": 2,
        "Contrôle orienté": 4,
        "Tir": 5,
        "Vitesse": 5,
        "Agilité": 4,
        "Endurance": 3,
        "Intelligence de jeu": 3,
        "Placement": 3,
        "Jeu collectif": 3,
        "Engagement": 0,
        "Leadership": 0,
        "Attitude / Comportement": 4,
    },
}
